### ISSUE TITLE
レビュー

### ISSUE THREAD

**Issue by kondomas1class** [UTokyo-SDP/ex-02-g19-32#5]
現状のGETなどの実装において、
/id/:id
のみならず、以下のようなアクセスに対しても正常終了してしまいます。
/other/:id

これを防ぐためにも、/id/まで一致したリクエストにのみ200レスポンスを返すよう条件付けする必要があります。

**Comment by shionhonda** [comment]
Thanks for your comment!
We updated the repository so it addresses the issue.
